# Generated by Django 4.2.1 on 2023-06-30 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_amountingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.AmountIngredient', to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(1, message='Минимальное кол-во ингредиентов 1')], verbose_name='Ингредиенты'),
        ),
    ]
