# Generated by Django 4.2.1 on 2023-07-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountingredient',
            name='recipe_ingredient_constraint',
        ),
    ]
