# Generated by Django 4.2.1 on 2023-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_amountingredient_recipe_ingredient_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='recipe_ingredient_constraint'),
        ),
    ]
